<!-- jquery plugins here-->
<script src="{{ asset('frontoffice/js/jquery-1.12.1.min.js') }}"></script>
<!-- popper js -->
<script src="{{ asset('frontoffice/js/popper.min.js') }}"></script>
<!-- bootstrap js -->
<script src="{{ asset('frontoffice/js/bootstrap.min.js') }}"></script>
<!-- easing js -->
<script src="{{ asset('frontoffice/js/jquery.magnific-popup.js') }}"></script>
<!-- swiper js -->
<script src="{{ asset('frontoffice/js/swiper.min.js') }}"></script>
<!-- swiper js -->
<script src="{{ asset('frontoffice/js/masonry.pkgd.js') }}"></script>
<!-- particles js -->
<script src="{{ asset('frontoffice/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('frontoffice/js/jquery.nice-select.min.js') }}"></script>
<!-- slick js -->
<script src="{{ asset('frontoffice/js/slick.min.js') }}"></script>
<script src="{{ asset('frontoffice/js/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('frontoffice/js/waypoints.min.js') }}"></script>
<script src="{{ asset('frontoffice/js/contact.js') }}"></script>
<script src="{{ asset('frontoffice/js/jquery.ajaxchimp.min.js') }}"></script>
<script src="{{ asset('frontoffice/js/jquery.form.js') }}"></script>
<script src="{{ asset('frontoffice/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('frontoffice/js/mail-script.js') }}"></script>
<!-- custom js -->
<script src="{{ asset('frontoffice/js/custom.js') }}"></script>
{{-- stack scripts --}}
@stack('scripts')
